# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '2de50ecc-9457-4055-9fee-0665a0a7fb4c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myarmtemplaterg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM-Test/azuredeploy-05.json'
    overrideParameters: '-projectName Arm1 -linkedTemplateUri https://raw.githubusercontent.com/savramovabpcs/AzureRmPipeline-repo/main/ARM-Test/azuredeploy.parameters.dev.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    addSpnToEnvironment: true
